### ISSUE TITLE
Can't seem to get this up and running?

### ISSUE THREAD

**Issue by phatmattbaker** [ausevo/ausevo.github.io#5]
Hi @thomased 

I'm the current secretary of AES and just trying to get this up and running.
I've got access to ausevo.com but there seems to be something a little off with ausevo.github.io -- not sure if you have any quick tips?

Thanks,
Matt

**Comment by thomased** [comment]
Hi @phatmattbaker,

The site seemed alive (and looked fairly sensible) on my end - http://ausevo.github.io (EDIT: not working now as I've updated the cname so it's redirecting). I haven't been involved for a couple of years and ~couple hundred commits, so not sure exactly what's meant to be on there, but it looks to be alive.

Or is it custom domain issues? In which case [github's guide](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site) is worth skimming through. I just fixed up the CNAME record in the repo, and tweaked some DNS settings on namecheap's end, but it can take a little time for everything to propagate. See how it looks tomorrow, otherwise yeah have a skim through that guide in case anything obscure was missed/changed (as I said, I haven't been in here for a while sorry!). That should be the main stuff sorted though...

Cheers,
Tom

**Comment by ausevo** [comment]
Thanks it is working fine. I think I understand how the github end of things works, I was just having some trouble with the namecheap end of things. Perhaps I did do the right thing but I didn't wait the right amount of time. Thanks for getting back to me. We are trying to bring it back to function - in terms of edits I presume I need to, eg edit index.md to change the markup that will then write an index.html?

I realise these are basic questions and happy enough to keep playing now but just was a little unsure if, eg, I should edit news.html directly or if there is a better/preferred way to do this. Thanks!

**Comment by ausevo** [comment]
Sorry, this was @phatmattbaker to @thomased !

**Comment by ausevo** [comment]
For example, just now I tried to edit a new .md file in the /news/ subdir to see if it would make a new post.

**Comment by ausevo** [comment]
Seems to have worked!

**Comment by thomased** [comment]
Great! And no that's all fair enough of course — it's not immediately intuitive. It looks like a lot has been changed & tweaked since I last looked, but yep in general you just edit the markdown files (`whatever.md`), then push those changes and they'll be converted & bounced up onto the respective webpage automatically in a minute or two.
